services:
    mariadb:
        image: yobasystems/alpine-mariadb:10.11.8
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=golang-boilerplate
            - MYSQL_USER=alterra
            - MYSQL_PASSWORD=alterra
        ports:
            - 3306:3306
        volumes:
            - ./data/docker/mysql:/var/lib/mysql
    redis:
        image: redis:7.4.2-alpine3.21
        hostname: redis
        command: ["redis-server", "--appendonly", "yes"]
        ports:
            - 6379:6379
        volumes:
            - ./data/docker/redis:/data
    zookeeper:
        image: confluentinc/cp-zookeeper:7.4.6
        hostname: zookeeper
        environment:
            - ZOOKEEPER_CLIENT_PORT=2181
            - ZOOKEEPER_SERVER_ID=1
            - ZOOKEEPER_SERVERS=zookeeper:2888:3888
        ports:
            - 2181:2181
    kafka:
        image: confluentinc/cp-kafka:7.4.6
        hostname: kafka
        environment:
            - KAFKA_BROKER_ID=1
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
            # PLAINTEXT_HOST should be your IP address and port (you can use localhost if using port 9092), 
            # as this is the address used by consumers (CLI & service) to access Kafka.
            - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
            - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
            - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
        ports:
            - 9092:9092
            - 29092:29092
        depends_on:
            - zookeeper